### ISSUE TITLE
Home화면 구현

### ISSUE THREAD

**Issue by teawon** [Google-Developer-Student-Clubs-TUK/2022-G.A.G-Android#5]
# Description
Home화면에 들어가는 기능구현

# Todo

- [x] 1차 ) 화면 UX/UI구현
- [ ] ViewModel, View 데이터 분리
- [ ] "현재 시간을 기준으로 다음 수업까지 N분" 시간 처리하기
